"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import type { EvaluatorType } from "@/core/benchmarks/types";
import type { PreviewResult } from "@/core/authoring/types";
import styles from "@/app/studio/studio.module.css";
import { useBenchmarkDraft } from "./use-benchmark-draft";

const steps = ["Basics", "Tasks", "Environment", "Evaluators", "Agents", "Review"] as const;
const evaluatorTypes: EvaluatorType[] = ["file", "schema", "command", "http", "browser", "numeric", "model-judge"];
type Provider = { id: string; name?: string; capabilities?: Record<string, boolean> };
type Credential = { ref: string; label?: string; source: string; configured: boolean };
const defaultConfig = (type: EvaluatorType): Record<string, unknown> => type === "file" ? { subject: "results.json", assertion: "present" } : type === "schema" ? { subject: "results.json", schema: "evaluators/results.schema.json" } : type === "command" ? { argv: ["python3", "/benchmark/evaluators/verify.py"] } : type === "http" ? { url: { fromEvaluator: "serve", output: "previewUrl" }, assertions: [{ type: "status", equals: 200 }] } : type === "browser" ? { actions: [{ type: "goto", url: { fromEvaluator: "serve", output: "previewUrl" } }, { type: "screenshot", role: "result" }] } : type === "numeric" ? { operation: "exact", actual: 1, expected: 1 } : { provider: "codex", rubric: "rubric.md", inputs: ["results.json"], sampling: { temperature: 0 } };

export function StudioShell() {
  const [state, dispatch] = useBenchmarkDraft(); const { draft } = state;
  const [step, setStep] = useState<(typeof steps)[number]>("Basics"); const [taskIndex, setTaskIndex] = useState(0);
  const [preview, setPreview] = useState<PreviewResult>(); const [checking, setChecking] = useState(false); const [message, setMessage] = useState("Unsaved draft");
  const [providers, setProviders] = useState<Provider[]>([]); const [credentials, setCredentials] = useState<Credential[]>([]); const [confirmed, setConfirmed] = useState(false); const [runId, setRunId] = useState<string>();
  const task = draft.tasks[taskIndex] ?? draft.tasks[0];
  const weight = task?.evaluators.filter((item) => item.enabled).reduce((sum, item) => sum + item.weight, 0) ?? 0;
  const edit = (next: typeof draft) => dispatch({ type: "edit", draft: next });
  const editTask = (patch: Partial<NonNullable<typeof task>>) => edit({ ...draft, tasks: draft.tasks.map((item, index) => index === taskIndex ? { ...item, ...patch } : item) });
  const graphValid = Boolean(task && task.evaluators.every((item) => item.prerequisites.every((id) => task.evaluators.some((candidate) => candidate.id === id))) && new Set(task.evaluators.map((item) => item.id)).size === task.evaluators.length);
  const environmentValid = Boolean(task && (task.allowedPrimitives.length > 0 || task.evaluators.every((item) => item.type === "model-judge")));
  const valid = Boolean(preview && preview.diagnostics.length === 0 && weight === 100 && graphValid && environmentValid);

  useEffect(() => { if (typeof fetch !== "function") return; void Promise.all([fetch("/api/providers").then((r) => r.json()), fetch("/api/credentials").then((r) => r.json())]).then(([p, c]) => { setProviders(p.data ?? []); setCredentials(c.data ?? []); }).catch(() => undefined); }, []);
  useEffect(() => { if (typeof fetch !== "function") return; const controller = new AbortController(); const timer = setTimeout(() => { setChecking(true); void fetch("/api/benchmarks/preview", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ draft }), signal: controller.signal }).then((r) => r.json()).then((body) => { setPreview(body.data); setMessage(body.data?.diagnostics?.length ? "Invalid draft" : "Preview is valid"); }).catch((error) => { if (error.name !== "AbortError") setMessage("Preview unavailable"); }).finally(() => setChecking(false)); }, 300); return () => { clearTimeout(timer); controller.abort(); }; }, [draft]);

  async function save() { setMessage("Saving…"); const url = state.revision ? `/api/benchmarks/${draft.id}` : "/api/benchmarks"; const body = state.revision ? { draft, expectedRevision: state.revision } : { draft }; const response = await fetch(url, { method: state.revision ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) { setMessage(payload.error?.code === "benchmark_conflict" ? `Conflict: ${(payload.error.changedPaths ?? []).join(", ")}` : payload.error?.message ?? "Save failed"); return; } dispatch({ type: "replace", draft: payload.data.draft, revision: payload.data.revision, snapshotDigest: payload.data.snapshotDigest }); setMessage("Saved"); }
  async function run(dryRun: boolean) { if (!task || !draft.agents[0]) return; setMessage(dryRun ? "Checking run plan…" : "Launching…"); const response = await fetch("/api/runs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ benchmarkId: draft.id, benchmarkDigest: state.snapshotDigest, taskId: task.id, agentId: draft.agents[0].id, dryRun }) }); const payload = await response.json(); if (!response.ok) return setMessage(`Run blocked: ${payload.error ?? "request failed"}`); if (dryRun) setMessage(`Dry run: ${payload.plan?.primitives?.join(", ") || "model only"}; max ${payload.estimatedMaximumMinutes} min`); else { setRunId(payload.id); setMessage("Run queued"); } }

  const editor = (() => {
    if (step === "Basics") return <section className={styles.panel}><h2>Benchmark basics</h2><label className={styles.field}>ID<input value={draft.id} onChange={(e) => edit({ ...draft, id: e.target.value })} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><label className={styles.field}>Name<input value={draft.name} onChange={(e) => edit({ ...draft, name: e.target.value })} /></label><div className={styles.row}><label className={styles.field}>Version<input value={draft.version} onChange={(e) => edit({ ...draft, version: e.target.value })} /></label><label className={styles.field}>Max concurrency<input type="number" min="1" value={draft.defaults.maxConcurrency} onChange={(e) => edit({ ...draft, defaults: { ...draft.defaults, maxConcurrency: Number(e.target.value) } })} /></label></div><label className={styles.field}>Description<textarea value={draft.description ?? ""} onChange={(e) => edit({ ...draft, description: e.target.value })} /></label></section>;
    if (step === "Tasks") return <section className={styles.panel}><h2>Tasks</h2><div className={styles.cards}>{draft.tasks.map((item, index) => <button className={styles.card} key={item.id} onClick={() => setTaskIndex(index)}>{item.name} · {item.id}</button>)}</div>{task ? <><label className={styles.field}>Task ID<input value={task.id} onChange={(e) => editTask({ id: e.target.value })} /></label><label className={styles.field}>Task name<input value={task.name} onChange={(e) => editTask({ name: e.target.value })} /></label><label className={styles.field}>Prompt<textarea value={task.prompt} onChange={(e) => editTask({ prompt: e.target.value })} /></label></> : null}<div className={styles.actions}><button onClick={() => { const n = draft.tasks.length + 1; edit({ ...draft, tasks: [...draft.tasks, { ...draft.tasks[0], id: `task-${n}`, name: `Task ${n}`, evaluators: draft.tasks[0].evaluators.map((x) => ({ ...x })) }] }); setTaskIndex(draft.tasks.length); }}>Add task</button><button onClick={() => task && edit({ ...draft, tasks: [...draft.tasks, { ...task, id: `${task.id}-copy`, name: `${task.name} copy`, evaluators: task.evaluators.map((x) => ({ ...x })) }] })}>Duplicate</button></div></section>;
    if (step === "Environment" && task) return <section className={styles.panel}><h2>Environment policy</h2><p className="retention-note">The agent chooses among the primitives you allow. Evaluators independently provision verifier-owned resources.</p><div className={styles.checks}>{(["browser", "sandbox", "desktop"] as const).map((primitive) => <label key={primitive}><input type="checkbox" checked={task.allowedPrimitives.includes(primitive)} onChange={() => editTask({ allowedPrimitives: task.allowedPrimitives.includes(primitive) ? task.allowedPrimitives.filter((p) => p !== primitive) : [...task.allowedPrimitives, primitive] })} />{primitive}</label>)}</div><div className={styles.row}>{Object.entries(task.resourceLimits).map(([key, value]) => <label className={styles.field} key={key}>{key}<input type="number" min="0" value={value} onChange={(e) => editTask({ resourceLimits: { ...task.resourceLimits, [key]: Number(e.target.value) } })} /></label>)}</div></section>;
    if (step === "Evaluators" && task) return <section className={styles.panel}><h2>Evaluators · {weight} / 100</h2>{!graphValid ? <p className="failure-banner">Evaluator IDs and prerequisites must form a valid graph.</p> : null}<div className={styles.cards}>{task.evaluators.map((item, index) => <article className={styles.card} key={`${item.id}-${index}`}><header><strong>{item.id}</strong><span>{item.type}</span></header><div className={styles.row}><label className={styles.field}>ID<input value={item.id} onChange={(e) => editTask({ evaluators: task.evaluators.map((x, i) => i === index ? { ...x, id: e.target.value } : x) })} /></label><label className={styles.field}>Weight<input type="number" min="0" max="100" value={item.weight} onChange={(e) => editTask({ evaluators: task.evaluators.map((x, i) => i === index ? { ...x, weight: Number(e.target.value) } : x) })} /></label></div><label className={styles.field}>Prerequisites (comma separated)<input value={item.prerequisites.join(", ")} onChange={(e) => editTask({ evaluators: task.evaluators.map((x, i) => i === index ? { ...x, prerequisites: e.target.value.split(",").map((v) => v.trim()).filter(Boolean) } : x) })} /></label><label className={styles.field}>Configuration JSON<textarea key={JSON.stringify(item.config)} defaultValue={JSON.stringify(item.config, null, 2)} onBlur={(e) => { try { const config = JSON.parse(e.target.value); editTask({ evaluators: task.evaluators.map((x, i) => i === index ? { ...x, config } : x) }); } catch { setMessage(`Invalid JSON for ${item.id}`); } }} /></label>{item.type === "command" && item.config.network === true ? <p className="failure-banner">Network access is enabled for this evaluator.</p> : null}</article>)}</div><div className={styles.actions}><select aria-label="Evaluator type" id="new-evaluator-type">{evaluatorTypes.map((type) => <option key={type} value={type}>{type}</option>)}</select><button onClick={() => { const select = document.querySelector<HTMLSelectElement>("#new-evaluator-type"); const type = (select?.value ?? "file") as EvaluatorType; editTask({ evaluators: [...task.evaluators, { id: `${type}-${task.evaluators.length + 1}`, type, weight: 0, enabled: true, prerequisites: [], config: defaultConfig(type) }] }); }}>Add evaluator</button></div></section>;
    if (step === "Agents") return <section className={styles.panel}><h2>Agent presets</h2>{draft.agents.map((agent, index) => <article className={styles.card} key={agent.id}><label className={styles.field}>Agent ID<input value={agent.id} onChange={(e) => edit({ ...draft, agents: draft.agents.map((x, i) => i === index ? { ...x, id: e.target.value } : x) })} /></label><label className={styles.field}>Provider<select value={agent.provider} onChange={(e) => edit({ ...draft, agents: draft.agents.map((x, i) => i === index ? { ...x, provider: e.target.value } : x) })}>{(providers.length ? providers : [{ id: "codex" }, { id: "anthropic" }, { id: "openai-compatible" }, { id: "executable-jsonl" }]).map((p) => <option key={p.id} value={p.id}>{p.name ?? p.id}</option>)}</select></label><label className={styles.field}>Model<input value={agent.model ?? ""} onChange={(e) => edit({ ...draft, agents: draft.agents.map((x, i) => i === index ? { ...x, model: e.target.value } : x) })} /></label><label className={styles.field}>Credential reference<select value={agent.credential ?? ""} onChange={(e) => edit({ ...draft, agents: draft.agents.map((x, i) => i === index ? { ...x, credential: e.target.value || undefined } : x) })}><option value="">None / local sign-in</option>{credentials.map((c) => <option key={c.ref} value={c.ref}>{c.label ?? c.ref} · {c.configured ? "configured" : "missing"}</option>)}</select></label></article>)}</section>;
    return <section className={styles.panel}><h2>Review</h2><dl className="metadata-panel"><div><dt>Tasks × agents</dt><dd>{draft.tasks.length} × {draft.agents.length}</dd></div><div><dt>Evaluator points</dt><dd>{weight} / 100</dd></div><div><dt>Snapshot</dt><dd>{preview?.snapshotDigest?.slice(0, 16) || "Checking"}</dd></div><div><dt>Model judges</dt><dd>{task?.evaluators.filter((e) => e.type === "model-judge").reduce((s, e) => s + e.weight, 0) ?? 0} points</dd></div></dl><label className={styles.checks}><input type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} />I understand this run can consume provider and Solari credits</label></section>;
  })();

  return <main className={styles.page}><header className={styles.title}><h1>Benchmark Studio</h1><p>Author portable agent tasks, evaluator graphs, and provider presets as canonical files.</p></header><p className={styles.mobileNote}>Full editing needs a desktop-sized window. Generated files remain available through the API.</p><div className={styles.grid}><nav className={styles.steps} aria-label="Studio steps">{steps.map((name) => <button key={name} data-active={step === name} onClick={() => setStep(name)}>{name}</button>)}</nav><div className={styles.editor}>{editor}</div><section className={styles.preview} aria-label="Generated files"><h2>Generated files</h2><div className={styles.fileList}>{preview?.files.map((file) => <article className={styles.file} key={file.path}><strong>{file.path} · {file.language}</strong><pre>{file.contents}</pre></article>) ?? <p className="empty-state">Preview appears after validation.</p>}</div></section></div><footer className={styles.footer}><p role="status" aria-live="polite"><span className={valid ? styles.valid : styles.invalid}>{checking ? "Checking" : valid ? "Valid" : "Unsaved"}</span> · {message} · {preview?.snapshotDigest?.slice(0, 12) || "no snapshot"}</p><button onClick={() => void save()} disabled={!valid || checking}>Save</button><button onClick={() => void run(true)} disabled={!state.revision || !valid}>Dry run</button><button className={styles.primary} onClick={() => void run(false)} disabled={!state.revision || !valid || !confirmed}>Run</button>{runId ? <Link href={`/runs/${runId}`}>View run →</Link> : null}</footer></main>;
}
